import React from 'react';
import { 
  X, 
  Printer, 
  Download, 
  FileText, 
  ShieldCheck, 
  CheckCircle2, 
  XCircle, 
  AlertTriangle,
  Building
} from 'lucide-react';

export default function ReportModal({ tenderDetails, bidders, onClose }) {
  const handlePrint = () => {
    window.print();
  };

  const qualified = bidders?.filter(b => b.verificationSummary.officerDecision?.status === 'QUALIFIED') || [];
  const clarifications = bidders?.filter(b => b.verificationSummary.officerDecision?.status === 'CLARIFICATION_REQUESTED') || [];
  const disqualified = bidders?.filter(b => b.verificationSummary.officerDecision?.status === 'DISQUALIFIED') || [];
  const pending = bidders?.filter(b => !b.verificationSummary.officerDecision || b.verificationSummary.officerDecision.status === 'PENDING_OFFICER_REVIEW') || [];

  return (
    <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-2 sm:p-4 overflow-y-auto">
      <div className="glass-panel w-full max-w-5xl rounded-2xl border border-slate-700 shadow-2xl bg-[#091122]/95 my-auto overflow-hidden animate-in fade-in zoom-in duration-200">
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-slate-800 bg-[#060B16] flex items-center justify-between print:hidden">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-600/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold text-white tracking-tight">
                Official GeM Technical Compliance & Verification Report
              </h2>
              <p className="text-xs text-slate-400">
                Executive Tender Evaluation Sheet with AI statutory evidence
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-blue-600 hover:bg-blue-500 text-white shadow-md transition-all flex items-center gap-1.5 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save as PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Report Document Body */}
        <div className="p-6 sm:p-8 max-h-[80vh] overflow-y-auto space-y-6 text-xs text-slate-200 print:text-black print:bg-white print:p-0">
          {/* Official Letterhead */}
          <div className="text-center border-b border-slate-700 pb-4 space-y-1">
            <div className="font-bold text-sm tracking-widest text-slate-300 uppercase">
              GOVERNMENT OF INDIA • GOVERNMENT e-MARKETPLACE (GeM)
            </div>
            <h1 className="text-base font-extrabold text-white">
              TECHNICAL EVALUATION & STATUTORY COMPLIANCE ASSESSMENT REPORT
            </h1>
            <p className="text-[11px] text-slate-400">
              Generated by Autonomous AI Verification Engine in compliance with GFR 2017 & PPP-MII Orders
            </p>
          </div>

          {/* Tender Metadata */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-900/60 p-4 rounded-xl border border-slate-800 text-[11px]">
            <div>
              <span className="text-slate-400 block">Tender ID:</span>
              <strong className="text-slate-100 font-mono">{tenderDetails?.tenderId || 'GEM/2026/B/882194'}</strong>
            </div>
            <div>
              <span className="text-slate-400 block">Buyer Ministry / CPSE:</span>
              <strong className="text-slate-100">{tenderDetails?.buyerOrg || 'Ministry of Electronics & IT'}</strong>
            </div>
            <div>
              <span className="text-slate-400 block">Estimated Tender Value:</span>
              <strong className="text-emerald-400 font-mono">{tenderDetails?.estimatedValue || '₹ 14.50 Cr'}</strong>
            </div>
            <div>
              <span className="text-slate-400 block">Date of Evaluation:</span>
              <strong className="text-slate-100">{new Date().toLocaleDateString('en-IN')}</strong>
            </div>
          </div>

          {/* Evaluation Summary Statistics */}
          <div className="grid grid-cols-4 gap-2 text-center">
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
              <span className="text-[10px] text-slate-400 uppercase font-semibold">Total Received</span>
              <div className="text-lg font-bold text-white font-mono">{bidders?.length || 0}</div>
            </div>
            <div className="p-2.5 rounded-lg bg-emerald-950/40 border border-emerald-800/60">
              <span className="text-[10px] text-emerald-400 uppercase font-semibold">Qualified</span>
              <div className="text-lg font-bold text-emerald-400 font-mono">{qualified.length}</div>
            </div>
            <div className="p-2.5 rounded-lg bg-amber-950/40 border border-amber-800/60">
              <span className="text-[10px] text-amber-400 uppercase font-semibold">Clarifications</span>
              <div className="text-lg font-bold text-amber-400 font-mono">{clarifications.length}</div>
            </div>
            <div className="p-2.5 rounded-lg bg-red-950/40 border border-red-800/60">
              <span className="text-[10px] text-red-400 uppercase font-semibold">Disqualified</span>
              <div className="text-lg font-bold text-red-400 font-mono">{disqualified.length}</div>
            </div>
          </div>

          {/* Detailed Bidders Evaluation Matrix */}
          <div className="space-y-2">
            <h3 className="font-bold text-slate-300 uppercase tracking-wider text-[11px]">
              Bidder-Wise Statutory Verification Matrix
            </h3>
            <table className="w-full text-left text-[11px] border border-slate-800 rounded-lg overflow-hidden">
              <thead className="bg-slate-900 text-slate-400 font-semibold border-b border-slate-800">
                <tr>
                  <th className="p-2.5">Bidder & IDs</th>
                  <th className="p-2.5">Category & MII</th>
                  <th className="p-2.5 text-center">Score</th>
                  <th className="p-2.5 text-center">Risk Level</th>
                  <th className="p-2.5">AI Statutory Summary & Flags</th>
                  <th className="p-2.5">Officer Verdict</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {bidders?.map((bidder) => (
                  <tr key={bidder.id} className="hover:bg-slate-900/40">
                    <td className="p-2.5 font-medium">
                      <div className="text-slate-100 font-semibold">{bidder.bidderName}</div>
                      <div className="text-[10px] text-slate-400 font-mono">PAN: {bidder.pan} | GST: {bidder.gstin}</div>
                    </td>
                    <td className="p-2.5">
                      <div>{bidder.claimedCategory}</div>
                      <div className="text-emerald-400 font-mono">MII: {bidder.localContentPercentage}%</div>
                    </td>
                    <td className="p-2.5 text-center font-mono font-bold">
                      {bidder.verificationSummary.complianceScore}%
                    </td>
                    <td className="p-2.5 text-center font-bold">
                      {bidder.verificationSummary.riskLevel}
                    </td>
                    <td className="p-2.5 max-w-xs text-slate-300 text-[10px]">
                      {bidder.verificationSummary.criticalFlags?.length > 0 ? (
                        <span className="text-red-400 font-medium">
                          {bidder.verificationSummary.criticalFlags.join(' | ')}
                        </span>
                      ) : (
                        bidder.verificationSummary.aiSummary
                      )}
                    </td>
                    <td className="p-2.5 font-semibold">
                      {bidder.verificationSummary.officerDecision?.status || 'PENDING_OFFICER_REVIEW'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Committee Sign-off Block */}
          <div className="pt-8 border-t border-slate-800 grid grid-cols-2 gap-8 text-[11px]">
            <div>
              <p className="text-slate-400">Technical Evaluation Officer:</p>
              <div className="mt-4 pt-4 border-t border-slate-700/60 font-semibold text-slate-200">
                Shri R. K. Verma, Sc. 'F'<br />
                <span className="text-slate-400 font-normal">Procurement Officer, GeM Evaluation Cell</span>
              </div>
            </div>

            <div className="text-right">
              <p className="text-slate-400">Competent Financial Authority:</p>
              <div className="mt-4 pt-4 border-t border-slate-700/60 font-semibold text-slate-200">
                Dr. S. Nair, Director (Procurement)<br />
                <span className="text-slate-400 font-normal">Ministry of Electronics & Information Technology</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
